### ISSUE TITLE
Object not found! NCBI_BlueBERT-Base, Uncased, PubMed

### ISSUE THREAD

**Issue by CaptainPenguin** [ncbi-nlp/bluebert#11]
I am trying to download BlueBERT-Base trained on only PubMed texts but it seems the link is not working.
![image](https://user-images.githubusercontent.com/36918802/70494561-da81bc80-1b5f-11ea-98ac-9750ddaefa0d.png)

**Comment by yfpeng** [comment]
Thanks for your email. I have fixed the link. Please try again.
