### ISSUE TITLE
No module named "bert"

### ISSUE THREAD

**Issue by BharathRajaGajula** [ncbi-nlp/bluebert#15]
Hello, 
After running the sentence similarity command for Sentence Similarity. I've received an error saying
"No module named bert". However the bert folder is at the correct place. I was unable to figure out why I am receiving error on line 23 of "run_bluebert_sts.py". I tried installing the bert using "pip install bert". It then throws an error saying that "modeling.py: No such file or directory". Then I installed the bert tensorflow version using "pip install bert-tensorflow". This clears the problem and pops a new problem like this.
"tensorflow.python.framework.errors_impl.NotFoundError: /vocab.txt; No such file or directory"

Can you please update the "requirements.txt". I couldn't find the version mentioned for tensorflow, i.e; 1.12.1. 

Thanks in Advance. Sorry for Inconvinience.

**Comment by yfpeng** [comment]
You don't need to install `bert` or `bert-tensorflow`. Instead, please add the working directory to `PYTHONPATH`. For example,

```bash
export PYTHONPATH=.
```
