### ISSUE TITLE
missing the vocab and config in pretrained model 

### ISSUE THREAD

**Issue by luomancs** [ncbi-nlp/bluebert#22]
hi

I would like to play with mt-bluebert-biomedical, but the download link only provide pt file, and the vocab and config files are missing, could you point to where I can get these two?
Thanks

**Comment by yfpeng** [comment]
It can be found at https://ftp.ncbi.nlm.nih.gov/pub/lu/Suppl/NCBI-BERT/NCBI_BERT_pubmed_uncased_L-12_H-768_A-12.zip

**Comment by luomancs** [comment]
thanks
