### ISSUE TITLE
NER Task on sample data

### ISSUE THREAD

**Issue by raghavbali** [ncbi-nlp/bluebert#26]
First of all, thank you @yfpeng and team for sharing your work. 
I had a query regarding using your scripts for NER task on sample data. As mentioned in issue #14 , I set train and eval options as false. The model processes data but generates no labels in the output file.
Could you highlight with the help on one example on how the input file should be and what would be the expected output?

Note: For testing purpose I even picked one example from the train set itself but still no output was observed

Thanks :)

**Comment by yfpeng** [comment]
Please try the test data at https://github.com/ncbi-nlp/BLUE_Benchmark/releases/download/0.1/bert_data.zip
