### ISSUE TITLE
How to Interpret the results of Relation Extraction?

### ISSUE THREAD

**Issue by BharathRajaGajula** [ncbi-nlp/bluebert#28]
After finishing the relation extraction operation for Chemprot Data. I get one tensorflow record and one tsv file. which is as follows.

**0.15294948	0.14690137	0.14512947	0.17709649	0.15383159	0.22409162
0.17051792	0.11182242	0.13569161	0.20062451	0.17994083	0.20140274
0.15868504	0.12534	0.13230026	0.16700414	0.17487246	0.24179816
0.15179233	0.15275687	0.1445464	0.18002915	0.15485005	0.21602511
0.1666515	0.112129934	0.12779407	0.16605248	0.17233992	0.25503212
0.17778598	0.1046794	0.120703295	0.16985807	0.1723527	0.25462052
0.16187875	0.11779226	0.13078773	0.16470376	0.17073172	0.25410575
0.16386983	0.11533519	0.13250493	0.16242501	0.17533559	0.25052953
0.16774821	0.11089808	0.13004696	0.16742839	0.17313573	0.25074264
0.17160876	0.10854226	0.12566698	0.16681188	0.17577308	0.251597
0.16189644	0.11701936	0.1346444	0.16580313	0.17096885	0.24966782
0.16152743	0.11757539	0.13271543	0.16380313	0.17377672	0.25060192
0.16656019	0.111814655	0.12732682	0.16468228	0.17510706	0.25450897
0.16650678	0.11021362	0.12661286	0.16736448	0.17467242	0.25462982
0.16048956	0.1193142	0.13183114	0.16296855	0.17130655	0.25409
0.1627501	0.112531364	0.12947361	0.16601284	0.17675503	0.25247702
0.15960562	0.11962788	0.1316634	0.1611976	0.17152742	0.2563781
0.16427976	0.112791955	0.12961149	0.16529398	0.17306624	0.2549565
0.15768206	0.12637071	0.13386849	0.16196251	0.16626643	0.25384983
0.15626168	0.12293934	0.13550161	0.16331881	0.16819012	0.2537883
0.1596326	0.121414356	0.13156259	0.16039251	0.1704628	0.25653514
0.16387884	0.11341449	0.12954234	0.16422358	0.17295827	0.25598237
0.15796445	0.127367	0.13383277	0.16219005	0.16565523	0.25299048
0.15737453	0.12230895	0.13421234	0.16285665	0.16942641	0.25382107
0.16121775	0.11749335	0.13174683	0.1615969	0.17064542	0.25729972
0.16171923	0.115740985	0.13092318	0.16363151	0.17172872	0.25625637
0.15772855	0.12557307	0.13428524	0.16082649	0.16551289	0.25607374
0.16506064	0.11239521	0.12870485	0.16525626	0.17356135	0.2550217
0.16727306	0.11162333	0.12815087	0.16378869	0.17512858	0.25403544
0.16821328	0.10925984	0.12688008	0.16718858	0.1744711	0.25398713
0.16123983	0.119652875	0.13235311	0.16205864	0.17105964	0.25363597
0.16371804	0.11169157	0.12968682	0.16627903	0.17704971	0.2515748
0.16859773	0.11070727	0.127372	0.16412714	0.17533523	0.25386068**

how do I interpret the results?

**Comment by yfpeng** [comment]
Each column represents the probability of the relation type defined in `get_labels` in order: https://github.com/ncbi-nlp/bluebert/blob/16f2f8a2c98b2299acd1c0d2a9bd889e7dbdc247/bluebert/run_bluebert.py#L252
