### ISSUE TITLE
No paper link

### ISSUE THREAD

**Issue by rodrigonogueira4** [ncbi-nlp/bluebert#3]
There is no link to the paper in the README.md file.

BTW, awesome work!

**Comment by yfpeng** [comment]
The paper is in the "Citing NCBI BERT" section.

**Comment by rodrigonogueira4** [comment]
Sorry, I was referring to the 10th line in README.md:
"Please refer to our paper [Transfer Learning in Biomedical Natural Language Processing: An Evaluation of BERT and ELMo on Ten Benchmarking Datasets]() for more details."

**Comment by yfpeng** [comment]
It is fixed. Many thanks indeed!
