### ISSUE TITLE
Need setup.py file for specifying dependency to bluebert repo

### ISSUE THREAD

**Issue by itsmemala** [ncbi-nlp/bluebert#33]
My repo has a dependency on the bluebert repo and I'm trying to specify the dependency using dependency_links in my setup.cfg file and using install_command in my tox.ini file. The install_command fails because the bluebert repo does not have a setup.py file. Would it be possible for you to create one? If not, would you know how I can clone the repo in my tox.ini file without error?

**Comment by yfpeng** [comment]
You can get dependencies from `requirements.txt`.
