### ISSUE TITLE
ERROR when torch.load("pytoch_model.bin") downloaded from huggingface

### ISSUE THREAD

**Issue by yolochai** [ncbi-nlp/bluebert#36]
I failed to torch.load the pytorch models downloaded from huggingface:
https://huggingface.co/bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12

the error info is:
ValueError: invalid literal for int() with base 8: 'rebuild_'

did anyone meet this problem?

**Comment by yfpeng** [comment]
I think it is a bug in the transformers package: https://github.com/huggingface/transformers/issues/2420

**Comment by yolochai** [comment]
> huggingface/transformers#2420



> I think it is a bug in the transformers package: [huggingface/transformers#2420](https://github.com/huggingface/transformers/issues/2420)

I don't think it's a problem with transformers package. I tried to use "torch.load" directly as follows but also got the same ERROR. 


import torch
data = torch.load("pytoch_model.bin")

**Comment by yfpeng** [comment]
I didn't find the error. I use transformers==3.4.0 and torch==1.7.0.

```bash
>>> tokenizer = AutoTokenizer.from_pretrained("bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12")
Downloading: 100%|██████████████████████████████████████████████████████████████████████| 313/313 [00:00<00:00, 395kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 2.91MB/s]
>>> model = AutoModel.from_pretrained("bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12")
Downloading: 100%|███████████████████████████████████████████████████████████████████| 441M/441M [01:11<00:00, 6.17MB/s]
>>>
```

**Comment by yolochai** [comment]
> I didn't find the error. I use transformers==3.4.0 and torch==1.7.0.
> 
> ```shell
> >>> tokenizer = AutoTokenizer.from_pretrained("bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12")
> Downloading: 100%|██████████████████████████████████████████████████████████████████████| 313/313 [00:00<00:00, 395kB/s]
> Downloading: 100%|███████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 2.91MB/s]
> >>> model = AutoModel.from_pretrained("bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12")
> Downloading: 100%|███████████████████████████████████████████████████████████████████| 441M/441M [01:11<00:00, 6.17MB/s]
> >>>
> ```
GOT IT. It is the problem of the pytorch version
I could load the file successfully using torch=1.7.0
Thank you soooo much!
