### ISSUE TITLE
Why are test labels always `'neutral'`?

### ISSUE THREAD

**Issue by seanswyi** [ncbi-nlp/bluebert#41]
Hi. I'm referring to line #295 in `run_bluebert.py`. I noticed that if the setting is `test`, then the labels are all `neutral`. What is the reason for this? According to the NLI data processors on places like HuggingFace, it seems it would be appropriate to set the labels to `None` if it's test. Please let me know if I'm mistaken. Thanks!

https://github.com/ncbi-nlp/bluebert/blob/ccc828c74e0eed942fd1ececff3638babc38269c/bluebert/run_bluebert.py#L295

**Comment by yfpeng** [comment]
Probably you are right. I don't think it matters.
