### ISSUE TITLE
How did you pre-train the NCBI abstract data exactly ?

### ISSUE THREAD

**Issue by zhouyunyun11** [ncbi-nlp/bluebert#5]
In your manuscript, your described like this: 
"We initialized BERT with pre-trained BERT provided by (Devlin et al., 2019). We then continue to pre-train the model, using the listed corpora".

Did you use BERT code completely re-train the NCBI abstract corpora? Or used BERT initial model and wordpiece strategy as bioBERT method?

**Comment by yfpeng** [comment]
We used BERT initial model and workpiece strategy.

**Comment by zhouyunyun11** [comment]
Do you mean you used the same strategy as Bio_BERT?

**Comment by zhouyunyun11** [comment]
Did you create your own vocab.txt file or use Google default one?

**Comment by yfpeng** [comment]
We used the Google default vocab.txt

**Comment by yfpeng** [comment]
I am not sure what you meant by "same strategy as Bio_BERT"
