### ISSUE TITLE
Input data for Document classification

### ISSUE THREAD

**Issue by adiv5** [ncbi-nlp/bluebert#9]
I have preprocessed MIMIC notes along with corresponding labels(multi-label classification task) in a pandas dataframe. How does sample data look like ? How to convert it into the format as required by the script `bluebert/run_bluebert_multi_labels.py`. ?
Also what is `aspect_value_list ` and `num_aspect` parameters?

**Comment by snjie209** [comment]
I was wondering how this was resolved @adiv5? I have the same questions as well. Thanks for reading!
